### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by jcubic** [faraazahmad/tisp#3]
I would be nice if there was build instruction so you can run it. Maybe in README. I'm not familiar with rust but I don't need to to run the compiler.

Do you plan on writing instruction? Sorry I'm not familiar with Cargo.

**Comment by faraazahmad** [comment]
Yeah I'm currently in the process of improving the readme, it'll have the build instruction and working example with dependencies

**Comment by faraazahmad** [comment]
I've updated the readme so closing this issue
